using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace randomdatagen
{
	public static class names
	{
		public static string betuk = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

		public static string[] varosok = new string[] {
			"Szekszárd", "Paks", "Dombóvár", "Bonyhád", "Tolna", "Dunaföldvár", "Tamási", "Bátaszék", "Simontornya", "Nagymányok", "Gyönk"
		};

		public static string[] fiunevek = new string[] {
			"Aba", "Adelmár", "Ajándok", "Almár", "András", "Ardó", "Artemon", "Avenár", "Abád", "Adeodát", "Ajtony", "Álmos", "André", "Árész", "Artúr", "Axel", "Abbás", "Ádér", "Akács", "Alpár", "Andrej", "Arétász", "Arvéd", "Azár", "Abdiás", "Ádin", "Ákos", "Alvián", "Andzseló", "Arián",
			"Ashraf", "Abod", "Adorján", "Alán", "Amand", "Aníziusz", "Ariton", "Asur", "Abony", "Adrián", "Alap", "Amator", "Antal", "Arkád", "Aszáf", "Abos", "Adriánó", "Alárd", "Ambos", "Antigon", "Árkád", "Aszter", "Abosa", "Agád", "Alarik", "Ambró", "Anton", "Árkos", "Asztrik", "Ábrahám",
			"Agamemnon", "Albert", "Ambrus", "Antónió", "Arlen", "Ata", "Ábrám", "Agapion", "Albin", "Amin", "Antos", "Árlen", "Atád", "Ábrán", "Agaton", "Aldán", "Amir", "Anzelm", "Armand", "Atakám", "Ábris", "Agenor", "Aldó", "Ámon", "Ányos", "Armandó", "Atanáz", "Absa", "Aggeus", "Áldor",
			"Ámor", "Apollinár", "Ármin", "Atilla", "Absolon", "Agmánd", "Alek", "Ámos", "Apolló", "Arnó", "Atlasz", "Acél", "Ágost", "Alen", "Anakin", "Apor", "Arnold", "Aton", "Achilles", "Ágoston", "Alex", "Anasztáz", "Apostol", "Arnót", "Atos", "Achillesz", "Ahillész", "Alexander", "Anatol", "Apród",
			"Áron", "Atosz", "Acsád", "Áhim", "Alfonz", "Andon", "Aracs", "Árpád", "Attila", "Adalbert", "Ahmed", "Alfréd", "Andor", "Arad", "Arszák", "Augusztusz", "Ádám", "Airton", "Algernon", "Andorás", "Aramisz", "Árszen", "Aurél", "Ádel", "Ajád", "Ali", "Andos", "Archibald", "Arszlán", "Aurélián",
			"Bács", "Barakony", "Bekes", "Bérc", "Bodomér", "Bors", "Bacsó", "Barangó", "Bekő", "Bercel", "Bodony", "Borsa", "Bagamér", "Bardó", "Béla", "Bere", "Bodor", "Botár", "Baján", "Barlám", "Belián", "Berec", "Bogát", "Botond", "Bajnok", "Barna", "Belizár", "Berend", "Bogdán", "Bottyán",
			"Bakács", "Barnabás", "Ben", "Berengár", "Bogumil", "Bozsidár", "Baksa", "Barót", "Bence", "Berény", "Bohumil", "Bozsó", "Bakta", "Bars", "Bende", "Beriszló", "Bohus", "Bökény", "Balabán", "Barsz", "Bendegúz", "Berke", "Boján", "Böngér", "Baladéva", "Barta", "Bendit", "Bernárd", "Bojta", "Brájen",
			"Balambér", "Bartal", "Bene", "Bernát", "Bojtor", "Brendon", "Balár", "Bartó", "Benedek", "Bertalan", "Bojtorján", "Brett", "Balassa", "Barton", "Benedikt", "Bertin", "Boldizsár", "Brúnó", "Balázs", "Bartos", "Benediktusz", "Bertold", "Boleszláv", "Brútusz", "Baldó", "Bató", "Benett", "Berton", "Bolivár", "Buda",
			"Baldvin", "Bátony", "Béni", "Bertram", "Bolyk", "Bulcsú", "Bálint", "Bátor", "Benignusz", "Berzsián", "Bonaventúra", "Buzád", "Balló", "Batu", "Benitó", "Bese", "Bonca", "Buzát", "Balmaz", "Batus", "Benjamin", "Beten", "Bongor", "Baltazár", "Bazil", "Benjámin", "Betlen", "Bonifác", "Bán", "Bazsó",
			"Benke", "Bihar", "Bónis", "Bandó", "Becse", "Benkő", "Boáz", "Borbás", "Bánk", "Bedecs", "Bennó", "Bocsárd", "Borisz", "Bános", "Bedő", "Benő", "Bod", "Borocs", "Barabás", "Beke", "Benvenútó", "Bodó", "Boromir", "Baracs", "Bekény", "Berárd", "Bódog", "Boroszló", "Cecilián", "Csaba",
			"Csejte", "Csikó", "Csombor", "Celesztin", "Csák", "Cseke", "Csingiz", "Csomor", "Cézár", "Csanád", "Csekő", "Csobád", "Csongor", "Ciceró", "Csát", "Csenger", "Csobajd", "Csörsz", "Ciprián", "Csatád", "Csépán", "Csobán", "Cirill", "Csatár", "Csepel", "Csolt", "Cirják", "Csató", "Cserjén", "Csoma",
			"Cirjék", "Csege", "Csete", "Círus", "Csegő", "Csetény", "Dagobert", "Deme", "Dioméd", "Drasek", "Dzsamal", "Dagomér", "Demény", "Ditmár", "Dukász", "Dzsasztin", "Dakó", "Demeter", "Doboka", "Dusán", "Dzsingiz", "Dalia", "Demjén", "Dókus", "Dzsínó", "Dalibor", "Dénes", "Doma", "Dzsúlió", "Dalton",
			"Dengezik", "Domán", "Damáz", "Denisz", "Dománd", "Damír", "Denton", "Domicián", "Damján", "Deodát", "Dominik", "Damos", "Derel", "Domokos", "Dániel", "Ders", "Domonkos", "Daniló", "Derzs", "Domos", "Dános", "Dés", "Donald", "Dante", "Detre", "Donát", "Darel", "Dévald", "Donátó", "Dárió",
			"Devecser", "Dorián", "Dárius", "Dezsér", "Dorion", "Dáriusz", "Dezsider", "Dormán", "Darnel", "Dezső", "Dormánd", "Dasztin", "Diegó", "Dov", "Dávid", "Dienes", "Dózsa", "Décse", "Dilen", "Döme", "Deján", "Dilon", "Dömjén", "Dejte", "Dimitri", "Dömös", "Deli", "Dimitrij", "Dömötör", "Ében",
			"Eliot", "Ernák", "Ede", "Elizeus", "Erneszt", "Edekon", "Ellák", "Ernesztó", "Edgár", "Elmár", "Ernik", "Edmond", "Elmó", "Ernő", "Edmund", "Élon", "Ernye", "Edömér", "Előd", "Erős", "Edrik", "Elton", "Ervin", "Eduárd", "Emánuel", "Étán", "Eduárdó", "Emil", "Ete", "Edvárd",
			"Emilián", "Etele", "Edvin", "Emmett", "Etre", "Efraim", "Emőd", "Eugén", "Egbert", "Endre", "Euszták", "Egmont", "Éneás", "Eutim", "Egon", "Engelbert", "Évald", "Egyed", "Engelhard", "Evariszt", "Elád", "Énok", "Everard", "Elek", "Énók", "Ezékiel", "Elemér", "Enrikó", "Ezel", "Elián",
			"Enzó", "Ezra", "Éliás", "Erazmus", "Ézsaiás", "Eliél", "Erhard", "Eliézer", "Erik", "Elígiusz", "Erk", "Fábián", "Fausztusz", "Filep", "Flórián", "Frederik", "Fábió", "Fedor", "Filibert", "Flóris", "Frederíkó", "Fábiusz", "Felicián", "Filip", "Fodor", "Fremont", "Fabó", "Félix", "Filippó", "Folkus",
			"Fridolin", "Fabríció", "Ferdinánd", "Filomén", "Fóris", "Frigyes", "Fabrícius", "Ferenc", "Flavián", "Fortunát", "Frodó", "Fabríciusz", "Fernandó", "Flávió", "Fortunátó", "Fülöp", "Fajsz", "Fidél", "Fláviusz", "Frank", "Farkas", "Filemon", "Florentin", "Franklin", "Gábor", "Gedeon", "Gerjén", "Godó", "Gregor", "Gyárfás",
			"Gabos", "Gedő", "Germán", "Godvin", "Guidó", "Gyécsa", "Gábriel", "Gejza", "Gerold", "Gópál", "Gujdó", "Gyeke", "Gál", "Gellén", "Gerő", "Gorán", "Gusztáv", "Gyenes", "Gallusz", "Gellért", "Gerváz", "Gordon", "Günter", "Gyoma", "Gálos", "Geminián", "Gerzson", "Gorgiás", "Györe", "Gandalf",
			"Geraszim", "Géza", "Gotárd", "György", "Gara", "Geréb", "Gibárt", "Gotfrid", "Györk", "Gáspár", "Gereben", "Gida", "Gothárd", "Györke", "Gaszton", "Gergely", "Gilbert", "Gotlíb", "Győző", "Gazsó", "Gergő", "Gilgames", "Göncöl", "Gyula", "Gécsa", "Gerhárd", "Girót", "Gracián", "Gede", "Gobert",
			"Hadúr", "Harri", "Hermész", "Honorát", "Hugó", "Háfiz", "Hárs", "Hermiás", "Honorátusz", "Humbert", "Hájim", "Harsány", "Hermiusz", "Honóriusz", "Hunor", "Hamilkár", "Hartvig", "Herold", "Hont", "Hunyad", "Hamza", "Hasszán", "Hetény", "Horác", "Hümér", "Hannibál", "Hektor", "Hiador", "Horáció", "Hannó",
			"Heliodor", "Hilár", "Horáciusz", "Harald", "Héliosz", "Hiláriusz", "Horka", "Hari", "Helmut", "Hilmár", "Hős", "Harka", "Henrik", "Hippolit", "Huba", "Harkány", "Herbert", "Hódos", "Hubert", "Harlám", "Herkules", "Holló", "Hubertusz", "Herman", "Honor", "Ibrahim", "Iliász", "Ipoly", "Ixion", "Ibrány",
			"Illés", "Iréneusz", "Izaiás", "Ignác", "Ilmár", "Irnik", "Izidor", "Igor", "Imbert", "István", "Izmael", "Ilán", "Immánuel", "Isua", "Izor", "Ilárion", "Imre", "Itiel", "Izrael", "Ildefonz", "Ince", "Iván", "Izsák", "Ilián", "Indár", "Ivó", "Izsó", "Ivor", "Jábin", "Járfás",
			"Jetró", "Józsiás", "Jutas", "Jácint", "Jászon", "Joachim", "Józsua", "Jutocsa", "Jáfet", "Jávor", "Joáhim", "Józsué", "Juvenál", "Jagelló", "Jázon", "Joakim", "Júda", "Jáir", "Jefte", "Joákim", "Jukundusz", "Jakab", "Jelek", "Jób", "Julián", "Jákim", "Jenő", "Joel", "Juliánusz", "Jákó",
			"Jeremi", "Johanán", "Júliusz", "Jákob", "Jeremiás", "Jónás", "Junior", "Jakus", "Jermák", "Jonatán", "Jusztin", "János", "Jernő", "Jordán", "Jusztusz", "Január", "Jeromos", "Jozafát", "Juszuf", "Járed", "József", "Kaba", "Karcsa", "Kerény", "Kocsárd", "Kristóf", "Kabos", "Kardos", "Keresztély", "Kolen",
			"Krisztián", "Kada", "Karim", "Keresztes", "Kolin", "Krisztofer", "Kadicsa", "Karion", "Kerim", "Kolos", "Krizosztom", "Kadisa", "Kármán", "Kerubin", "Kolozs", "Krizsán", "Kadocsa", "Károly", "Késav", "Kolta", "Kund", "Kadosa", "Karsa", "Keszi", "Kolumbán", "Kunó", "Kajetán", "Kartal", "Kesző", "Kolumbusz",
			"Kurd", "Kájusz", "Kászon", "Ketel", "Kond", "Kurszán", "Kál", "Kasszián", "Keve", "Konor", "Kurt", "Káldor", "Kasztor", "Kevend", "Konrád", "Kusán", "Káleb", "Katapán", "Kevin", "Konstantin", "Kustyán", "Kálmán", "Kazimír", "Kilán", "Kont", "Kürt", "Kamill", "Kázmér", "Kilény", "Koppány",
			"Kventin", "Kamilló", "Keán", "Kilián", "Koridon", "Kán", "Keled", "Kilit", "Koriolán", "Kandid", "Kelemen", "Kirill", "Kornél", "Kanut", "Kelemér", "Kiron", "Korvin", "Kapisztrán", "Kelen", "Kitán", "Kos", "Kaplon", "Kelvin", "Klaudió", "Kósa", "Kaplony", "Kemenes", "Klaudiusz", "Kovrat", "Kapolcs",
			"Kende", "Klausz", "Kozma", "Kara", "Kenese", "Kleofás", "Kötöny", "Karácson", "Kenéz", "Kleon", "Kövecs", "Karád", "Kerecsen", "Klétus", "Krisna", "Laborc", "Lázó", "Leontin", "Lipót", "Lúciusz", "Ladomér", "Leander", "Leopold", "Lívió", "Ludvig", "Lajos", "Leandró", "Lestár", "Liviusz", "Lukács",
			"Lamar", "Leándrosz", "Levéd", "Líviusz", "Lüszien", "Lambert", "Lehel", "Levedi", "Lizander", "Lándor", "Lél", "Levente", "Loránd", "Lantos", "Lénárd", "Lévi", "Lóránd", "Largó", "Lénárt", "Liberátusz", "Lóránt", "Larion", "Leó", "Libériusz", "Lorenzó", "László", "Leon", "Libor", "Lotár", "Laurent",
			"Leonárd", "Libóriusz", "Lőrinc", "Lázár", "Leonárdó", "Linasz", "Lucián", "Leonidász", "Lionel", "Madocsa", "Markó", "Melhior", "Misa", "Magnusz", "Márkó", "Meliton", "Misel", "Magor", "Márkus", "Melkisédek", "Miske", "Majlát", "Márkusz", "Memno", "Modesztusz", "Majs", "Marót", "Ménás", "Mohamed", "Makabeus",
			"Marsal", "Mendel", "Móka", "Makár", "Martin", "Ménrót", "Mór", "Malakiás", "Marton", "Menyhért", "Morgan", "Malik", "Márton", "Merlin", "Móric", "Manassé", "Martos", "Merse", "Mózes", "Manfréd", "Marvin", "Metód", "Manó", "Máté", "Mihály", "Manszvét", "Mateusz", "Mika", "Manuel", "Mátyás",
			"Mikán", "Mánuel", "Mauríció", "Mike", "Marcel", "Mauró", "Mikeás", "Marcell", "Max", "Mikes", "Marcián", "Maxim", "Miklós", "Március", "Maximilián", "Mikó", "Marcselló", "Maximusz", "Miksa", "Marián", "Mazen", "Milán", "Marinusz", "Medárd", "Miló", "Márió", "Medox", "Milos", "Máriusz", "Megyer",
			"Mirkó", "Márk", "Melchior", "Miron", "Nándor", "Nelzon", "Nikétás", "Noel", "Nyék", "Napóleon", "Nemere", "Nikodémus", "Nónusz", "Nyikoláj", "Narcisszusz", "Némó", "Nikodémusz", "Norbert", "Náron", "Nepomuk", "Nikolasz", "Norisz", "Nasszer", "Nesztor", "Nimái", "Norman", "Nátán", "Nétus", "Nimród", "Norton",
			"Nátánael", "Nétusz", "Nitái", "Nataniel", "Nikander", "Noé", "Oberon", "Oleg", "Ormos", "Ozirisz", "Odiló", "Olivér", "Oros", "Ozmin", "Odin", "Omár", "Oszkár", "Ozor", "Odisszeusz", "Ompoly", "Oszlár", "Ozul", "Odó", "Omri", "Osszián", "Ozsvát", "Ódor", "Ond", "Oszvald", "Oguz",
			"Orbán", "Otelló", "Oktáv", "Orbó", "Otmár", "Oktávián", "Orda", "Otniel", "Olaf", "Oresztész", "Ottó", "Olavi", "Orfeusz", "Ottokár", "Oldamur", "Orion", "Oven", "Orlandó", "Ovídiusz", "Ödön", "Örkény", "Örkönd", "Örs", "Özséb", "Pál", "Pelbárt", "Petúr", "Piramusz", "Pálos", "Pellegrin",
			"Piládész", "Piusz", "Pamfil", "Pentele", "Pió", "Placid", "Pantaleon", "Periklész", "Platón", "Páris", "Perjámos", "Polidor", "Paszkál", "Péter", "Polikárp", "Patony", "Pető", "Pongor", "Patrícius", "Petres", "Pongrác", "Patrik", "Petrik", "Porfir", "Pázmán", "Petróniusz", "Pósa", "Pelágiusz", "Petur", "Prímusz",
			"Rabán", "Reginald", "Rókus", "Radamesz", "Regő", "Roland", "Radiszló", "Regös", "Rolf", "Radó", "Regős", "Román", "Radomér", "Remig", "Románó", "Rados", "Rémusz", "Romárió", "Radován", "Renátó", "Rómeó", "Radvány", "Renátusz", "Romuald", "Rafael", "René", "Romulusz", "Ráfis", "Réva", "Romvald",
			"Ragnar", "Rézmán", "Ron", "Rajmond", "Rezső", "Ronald", "Rajmund", "Richárd", "Ronaldó", "Rajnald", "Rihárd", "Ronel", "Ralf", "Rikárdó", "Ronen", "Ramirez", "Rinaldó", "Roni", "Ramiró", "Róbert", "Ruben", "Ramiz", "Robertó", "Rúben", "Ramón", "Robin", "Rudolf", "Ramszesz", "Robinzon", "Rúfusz",
			"Rápolt", "Rodel", "Rupert", "Rátold", "Roderik", "Ruszlán", "Raul", "Rodion", "Rusztem", "Razmus", "Rodrigó", "Rázsony", "Rokkó", "Salamon", "Sebő", "Simon", "Surány", "Sámson", "Sebők", "Sion", "Surd", "Samu", "Sejbán", "Sjám", "Suriel", "Sámuel", "Sém", "Solt", "Sükösd", "Sándor",
			"Semjén", "Solymár", "Sarel", "Simeon", "Sólyom", "Saul", "Som", "Sebes", "Soma", "Sebestyén", "Spartakusz", "Stefán", "Szabin", "Szente", "Szókratész", "Szabolcs", "Szeráf", "Szólát", "Szaján", "Szerénd", "Szolón", "Szalárd", "Szerénusz", "Szórád", "Szaléz", "Szergiusz", "Szovárd", "Szalók", "Szervác", "Szovát",
			"Szalvátor", "Szevér", "Szörénd", "Szalviusz", "Szeveréd", "Szörény", "Szamir", "Szeverián", "Szpartakusz", "Szandró", "Szeverin", "Szaniszló", "Szidor", "Szantiágó", "Szigfrid", "Szantínó", "Szilamér", "Szatmár", "Szilárd", "Szavér", "Szilas", "Szebáld", "Szilvánusz", "Szebasztián", "Szilver", "Szecső", "Szilvér", "Szedrik", "Szilveszter", "Szelemér",
			"Szilvió", "Szelestény", "Szilviusz", "Szelim", "Szindbád", "Szemere", "Szíriusz", "Szemír", "Szixtusz", "Szendrő", "Szofron", "Tacitusz", "Temes", "Tobán", "Taddeus", "Teó", "Tóbiás", "Tádé", "Teobald", "Tódor", "Tadeusz", "Teodor", "Toma", "Taksony", "Teofil", "Tomaj", "Talabér", "Terestyén", "Tomor", "Talabor",
			"Tétény", "Tonuzóba", "Talamér", "Tézeusz", "Torda", "Táltos", "Tibád", "Tordas", "Tamás", "Tibériusz", "Tormás", "Tankréd", "Tibold", "Torna", "Tar", "Tibor", "Torontál", "Taráz", "Tiborc", "Töhötöm", "Tarcal", "Ticián", "Tömör", "Tarcsa", "Tihamér", "Törtel", "Tardos", "Timon", "Trajánusz", "Tarján",
			"Timót", "Trevisz", "Tárkány", "Timóteus", "Trisztán", "Tarsa", "Timóteusz", "Tullió", "Tarzíciusz", "Timur", "Turul", "Tas", "Tirzusz", "Tuzson", "Tasnád", "Titán", "Tasziló", "Titusz", "Tege", "Tivadar", "Tegze", "Tiván", "Ubul", "Ulászló", "Urbán", "Údó", "Uldin", "Uriás", "Ugocsa", "Ulisszesz",
			"Uriel", "Ugod", "Ulpián", "Uros", "Ugor", "Ulrik", "Uzon", "Ugron", "Umbertó", "Uzor", "Upor", "Üllő", "Vadony", "Várkony", "Versény", "Vince", "Vojta", "Vajk", "Varsány", "Vértes", "Vincent", "Volfram", "Vajta", "Vászoly", "Viátor", "Virgil", "Vulkán", "Valdemár", "Vata", "Vid",
			"Vitálij", "Valdó", "Vazul", "Vida", "Vitális", "Valentin", "Vázsony", "Vidor", "Vitályos", "Valentínó", "Vejke", "Vidos", "Vitéz", "Valér", "Velek", "Vikram", "Vító", "Valérió", "Vencel", "Viktor", "Vitold", "Valter", "Vendel", "Vilibald", "Vitus", "Valton", "Verner", "Vilmos", "Vladimír", "Xavér",
			"Zádor", "Zéman", "Zoárd", "Zsadány", "Zágon", "Zénó", "Zobor", "Zserald", "Zajta", "Zente", "Zolta", "Zsigmond", "Zajzon", "Zerénd", "Zoltán", "Zsolt", "Zakariás", "Zerind", "Zólyom", "Zsombor", "Zakeus", "Zéta", "Zombor", "Zsongor", "Zala", "Zete", "Zongor", "Zsubor", "Zalán", "Zétény",
			"Zorán", "Zsülien", "Zámor", "Zeusz", "Zotmund", "Zaránd", "Zílió", "Zovárd", "Zdenkó", "Zimány", "Zovát", "Zebadiás", "Zuárd", "Zebulon", "Zuboly", "Zekő", "Zuriel"};


		public static string[] lanynevek = new string[] {
			"Abélia", "Adriána", "Ajna", "Alexandrina", "Alojzia", "Amina", "Angyalka", "Annamari", "Abiáta", "Adrianna", "Ajnácska", "Alexia", "Aloma", "Aminta", "Ani", "Annamária", "Abigél", "Adrienn", "Ajnó", "Alfonza", "Alóma", "Amira", "Ania", "Annamira", "Ada", "Áfonya", "Ajra", "Alfonzin", "Alvina", "Amrita",
			"Anica", "Annamíra", "Adala", "Áfra", "Ajsa", "Alfonzina", "Amábel", "Anada", "Anicéta", "Annaregina", "Adalberta", "Afrodita", "Ajtonka", "Alfréda", "Amadea", "Anaisz", "Aniella", "Annarita", "Adalbertina", "Afrodité", "Akaiéna", "Alica", "Amadil", "Anasztázia", "Anika", "Annaróza", "Adaora", "Agáta", "Akilina", "Alicia",
			"Amál", "Anatólia", "Anikó", "Annavera", "Adél", "Ági", "Alba", "Alícia", "Amália", "Ancilla", "Anilla", "Anni", "Adela", "Aglája", "Alberta", "Alida", "Amanda", "Anda", "Anima", "Annunciáta", "Adéla", "Aglent", "Albertin", "Alina", "Amarant", "Andelin", "Anina", "Anriett", "Adelaida", "Agnabella",
			"Albertina", "Alinda", "Amaranta", "Andelina", "Anissza", "Antea", "Adelgund", "Agnella", "Albina", "Alinka", "Amarill", "Andi", "Anita", "Antigoné", "Adelgunda", "Ágnes", "Alda", "Alirán", "Amarilla", "Andrea", "Anitra", "Antoanett", "Adelheid", "Agnéta", "Áldáska", "Alisa", "Amarillisz", "Androméda", "Anízia", "Antonella",
			"Adélia", "Ágosta", "Aldea", "Alitta", "Amáta", "Anélia", "Ánizs", "Antónia", "Adelin", "Ágota", "Álea", "Aliz", "Amázia", "Anelma", "Anka", "Antoniett", "Adelina", "Agrippína", "Aléna", "Alíz", "Ambrózia", "Anéta", "Ankisza", "Antonietta", "Adelinda", "Aida", "Aleszja", "Aliza", "Amelda", "Anett",
			"Anna", "Anzelma", "Adeodáta", "Aina", "Alesszia", "Allegra", "Ameli", "Anetta", "Annabel", "Apol", "Adina", "Ainó", "Alett", "Alma", "Amélia", "Angéla", "Annabell", "Apolka", "Admira", "Aira", "Aletta", "Almanda", "Amelita", "Angelika", "Annabella", "Apollinária", "Adolﬁna", "Aisa", "Alexa", "Almira",
			"Ametiszt", "Angelina", "Annakata", "Apollónia", "Adonika", "Aisah", "Alexandra", "Almiréna", "Amidala", "Angella", "Annaléna", "Aporka", "Adria", "Ajándék", "Alexandrin", "Aloé", "Amilla", "Angyal", "Annaliza", "Appia", "Áprilka", "Ari", "Arienn", "Árnika", "Asztrid", "Atika", "Aurea", "Arabella", "Ariadna", "Arika",
			"Arnolda", "Asztrida", "Atina", "Aurélia", "Aranka", "Ariadné", "Arikán", "Árpádina", "Atala", "Auguszta", "Auróra", "Arany", "Ariana", "Arina", "Artemisz", "Atalanta", "Augusztina", "Avarka", "Aranyka", "Arianna", "Arinka", "Artemízia", "Atália", "Aura", "Azálea", "Aranyos", "Ariéla", "Arita", "Árvácska", "Atanázia",
			"Azucséna", "Ariella", "Arlett", "Árven", "Aténa", "Azura", "Armanda", "Arzénia", "Aténé", "Azurea", "Armandina", "Asma", "Armida", "Aszpázia", "Armilla", "Asszunta", "Ármina", "Asztéria", "Babér", "Bebóra", "Bertolda", "Boglár", "Brunhilda", "Babett", "Béda", "Béta", "Boglárka", "Brünhild", "Babetta", "Begónia",
			"Betsabé", "Bojána", "Búzavirág", "Babiána", "Bejke", "Betta", "Bolda", "Babita", "Béke", "Betti", "Bonita", "Bagita", "Belinda", "Bettina", "Bora", "Bahar", "Bella", "Bianka", "Bóra", "Balbina", "Benáta", "Bibiána", "Borbála", "Balda", "Benedetta", "Bíbor", "Borbolya", "Balzsam", "Benedikta", "Bíbora",
			"Borcsa", "Bara", "Beneditta", "Bíboranna", "Bori", "Barack", "Benigna", "Bíborka", "Boris", "Baranka", "Benita", "Bié", "Boriska", "Barbara", "Benjamina", "Birgit", "Borka", "Barbarella", "Bereniké", "Biri", "Boróka", "Barka", "Berill", "Bítia", "Borostyán", "Bársony", "Berkenye", "Blandina", "Borsika", "Bársonyka",
			"Berna", "Blanka", "Bozsena", "Baucisz", "Bernadett", "Blazsena", "Bozsóka", "Bazilia", "Bernadetta", "Blondina", "Brenda", "Bea", "Bernarda", "Bóbita", "Brigitta", "Beáta", "Bernardina", "Bodza", "Britani", "Beatricse", "Berta", "Bogárka", "Britni", "Beatrisz", "Bertilla", "Bogáta", "Britta", "Beatrix", "Bertina", "Bogi",
			"Brunella", "Cecília", "Celina", "Cinderella", "Cipra", "Cecilla", "Cettina", "Cinella", "Cipriána", "Celerina", "Cezarin", "Cinka", "Ciprienn", "Celeszta", "Cezarina", "Cinna", "Cirilla", "Celesztina", "Cicelle", "Cinnia", "Citta", "Célia", "Ciklámen", "Cintia", "Cili", "Cipora", "Cilla", "Cippóra", "Csaga", "Cseperke",
			"Csinszka", "Csalka", "Csepke", "Csobánka", "Csende", "Csermely", "Csobilla", "Csendike", "Cserne", "Csoboka", "Csenge", "Csilla", "Csönge", "Csengele", "Csillag", "Csöre", "Csente", "Csillagvirág", "Dafna", "Delani", "Dina", "Dorit", "Dafné", "Delﬁna", "Dió", "Dorka", "Dália", "Délia", "Dionízia", "Dorkás",
			"Dalida", "Délibáb", "Diotíma", "Dorkász", "Dalla", "Delila", "Ditke", "Dormánka", "Dalma", "Delinda", "Ditta", "Dorotea", "Damajanti", "Delinke", "Ditte", "Doroti", "Damarisz", "Della", "Dolli", "Dorotina", "Damira", "Demetria", "Dolóresz", "Dorottya", "Damjána", "Denisza", "Dolorita", "Döníz", "Dana", "Denissza",
			"Doloróza", "Druzsiána", "Danica", "Deniza", "Domicella", "Dulcinea", "Daniela", "Derien", "Domiciána", "Dusánka", "Daniéla", "Detti", "Dominika", "Dusmáta", "Daniella", "Déva", "Dominka", "Danila", "Devínia", "Domitilla", "Danka", "Dezdemóna", "Donáta", "Danuta", "Dézi", "Donatella", "Dára", "Dezideráta", "Donna", "Dária",
			"Dezidéria", "Dóra", "Darina", "Dia", "Dorabella", "Darinka", "Diána", "Doren", "Darla", "Diandra", "Dorina", "Dea", "Diké", "Dorinka", "Debóra", "Dilara", "Dorisz", "Dzsamila", "Dzsenifer", "Dzsesszika", "Dzsamilla", "Dzsenna", "Dzsindzser", "Dzsenet", "Dzsenni", "Écska", "Elfrida", "Emili", "Ermelinda", "Eufrozina",
			"Éda", "Elga", "Emília", "Erna", "Eugénia", "Edda", "Eliána", "Emiliána", "Ernella", "Eulália", "Edentina", "Elif", "Emíra", "Erneszta", "Eunika", "Edina", "Elin", "Emma", "Ernesztin", "Euniké", "Edit", "Elina", "Emmaróza", "Ernesztina", "Euridiké", "Edmunda", "Elinor", "Emmi", "Ervina", "Európa",
			"Edna", "Eliz", "Emő", "Ervínia", "Eutímia", "Édra", "Eliza", "Emőke", "Erzsébet", "Euzébia", "Édua", "Elizabet", "Enciána", "Erzsi", "Éva", "Eduárda", "Elke", "Ené", "Esma", "Evangelina", "Edvarda", "Ella", "Enéh", "Estella", "Evelin", "Edvina", "Elli", "Enese", "Estilla", "Evelina",
			"Efﬁ", "Ellina", "Enet", "Eszmeralda", "Evetke", "Egberta", "Elma", "Enid", "Esztella", "Evica", "Eija", "Elmira", "Enikő", "Eszténa", "Evila", "Ekaterina", "Elvira", "Enna", "Eszter", "Evita", "Ékes", "Elza", "Eper", "Eta", "Evódia", "Eleanor", "Emanuéla", "Eperke", "Etel", "Evolet",
			"Elektra", "Emerencia", "Epifánia", "Etelka", "Elen", "Emerika", "Eponin", "Etka", "Elena", "Emerita", "Era", "Etta", "Eleni", "Emerka", "Erátó", "Etus", "Eleonóra", "Emese", "Erika", "Eudoxia", "Életke", "Émi", "Erina", "Eufémia", "Fabiána", "Felicitász", "Florina", "Fabióla", "Ferdinanda", "Florinda",
			"Fabrícia", "Fernanda", "Fortuna", "Fadett", "Fiametta", "Fortunáta", "Fahéj", "Fiamma", "Főbe", "Fáni", "Fidélia", "Franciska", "Fanna", "Filadelﬁa", "Franka", "Fanni", "Filippa", "Franni", "Fáta", "Fillisz", "Freja", "Fatima", "Filoméla", "Frézia", "Fatime", "Filoména", "Frida", "Fausztina", "Filotea", "Friderika",
			"Fébé", "Fióna", "Fruzsina", "Febrónia", "Fiorella", "Fulvia", "Federika", "Fioretta", "Fürtike", "Fedóra", "Firtos", "Füzér", "Fédra", "Flamina", "Füzike", "Fehér", "Flanna", "Fehéra", "Flávia", "Fehére", "Flóra", "Fehérke", "Floransz", "Felícia", "Florencia", "Feliciána", "Florentina", "Felicita", "Florianna", "Felicitás",
			"Florica", "Gabriella", "Gertrúdisz", "Gizella", "Gajána", "Gesztenye", "Glenda", "Galamb", "Gilberta", "Glória", "Galatea", "Gilda", "Godiva", "Galina", "Gina", "Golda", "Gardénia", "Giszmunda", "Goldina", "Géda", "Gitta", "Gordána", "Géla", "Giza", "Grácia", "Gemella", "Graciána", "Gemma", "Graciella", "Génia",
			"Gréta", "Genovéva", "Gréte", "Georgina", "Gréti", "Gerbera", "Grizelda", "Gerda", "Grizeldisz", "Gerle", "Gunda", "Gertrúd", "Gvendolin", "Gyémánt", "Gyömbér", "Gyöngyike", "Gyöngyvirág", "Gyopár", "Gyöngy", "Gyöngyös", "Györgyi", "Gyopárka", "Gyöngyi", "Gyöngyvér", "Györgyike", "Hadassa", "Hanni", "Helén", "Heszna", "Holli",
			"Hágár", "Hargita", "Heléna", "Hetti", "Honóra", "Hajna", "Hargitta", "Helga", "Hiacinta", "Honoráta", "Hajnácska", "Harmat", "Helka", "Hieronima", "Honória", "Hajnal", "Harmatka", "Hella", "Hilária", "Honorina", "Hajnalka", "Harriet", "Heni", "Hilda", "Honorka", "Hajni", "Havaska", "Henriett", "Hildegárd", "Horácia",
			"Hanga", "Hedda", "Henrietta", "Hildelita", "Hortenzia", "Hanka", "Hédi", "Héra", "Hilka", "Hóvirág", "Hanna", "Hedvig", "Hermia", "Hippia", "Huberta", "Hannadóra", "Heidi", "Hermina", "Hippolita", "Hunóra", "Hannaliza", "Héla", "Herta", "Hófehérke", "Hunorka", "Hannaróza", "Holda", "Ibolya", "Imola", "Ivon",
			"Ica", "Inana", "Ivonn", "Ida", "Indira", "Iza", "Idril", "Indra", "Izabel", "Iduna", "Inez", "Izabell", "Iﬁgénia", "Inge", "Izabella", "Ignácia", "Ingeborg", "Izaura", "Ila", "Ingrid", "Izidóra", "Ilang", "Inka", "Ízisz", "Ilda", "Innocencia", "Izméne", "Ildikó", "Ippolita", "Izolda",
			"Ilka", "Irén", "Izóra", "Illa", "Iréne", "Illangó", "Irina", "Ilma", "Iringó", "Ilon", "Írisz", "Ilona", "Irma", "Ilonka", "Isméria", "Ilus", "Itala", "Iluska", "Ivána", "Ilze", "Ivett", "Imelda", "Ivetta", "Immakuláta", "Ivica", "Imodzsen", "Ividő", "Imogén", "Ivola", "Jácinta",
			"Jerta", "Julietta", "Jáde", "Jeszénia", "Julilla", "Jádránka", "Jetta", "Julinka", "Jadviga", "Jetti", "Juliska", "Jáhel", "Johanna", "Julitta", "Jaina", "Johara", "Júnó", "Jakobina", "Jokébed", "Jusztícia", "Jamina", "Jolán", "Jusztina", "Jana", "Jolanda", "Jusztínia", "Janina", "Jolánta", "Jutka", "Janka",
			"Joli", "Jutta", "Jára", "Jolina", "Jarmila", "Jonka", "Jávorka", "Jordána", "Jázmin", "Joszina", "Jázmina", "Jována", "Jelena", "Jozefa", "Jelina", "Jozeﬁn", "Jelka", "Jozeﬁna", "Jella", "Józsa", "Jemima", "Judit", "Jenni", "Juli", "Jente", "Júlia", "Jerne", "Juliána", "Jeronima", "Julianna",
			"Kála", "Kasszandra", "Kincs", "Klió", "Krisztabell", "Kalina", "Kata", "Kincső", "Kloé", "Krisztiána", "Kalipszó", "Katalin", "Kinga", "Klotild", "Krisztina", "Kalli", "Katarina", "Kira", "Kolett", "Krizanta", "Kalliopé", "Katerina", "Kíra", "Koletta", "Kunigunda", "Kalliszta", "Kati", "Kiri", "Kolomba", "Küllikki",
			"Kámea", "Katica", "Kirilla", "Kolombina", "Küne", "Kamélia", "Katinka", "Kisanna", "Konkordia", "Kamilia", "Kató", "Kisó", "Konstancia", "Kamilla", "Katrin", "Kitana", "Konstantina", "Kandida", "Kátya", "Kitti", "Kora", "Karen", "Kelli", "Klára", "Korália", "Karin", "Kendra", "Klári", "Korall", "Karina",
			"Kenza", "Klarisz", "Kordélia", "Karitász", "Kéra", "Klarissza", "Korina", "Karla", "Kéren", "Klaudetta", "Korinna", "Karméla", "Kerka", "Klaudia", "Kornélia", "Karmelina", "Kersztin", "Klaudiána", "Koronilla", "Karmella", "Kerubina", "Klélia", "Kozett", "Kármen", "Késa", "Klemátisz", "Kozima", "Kármin", "Ketrin", "Klemencia",
			"Kökény", "Karola", "Kiara", "Klementin", "Kreola", "Karolin", "Kikinda", "Klementina", "Kreszcencia", "Karolina", "Kiliána", "Kleó", "Krimhilda", "Karolt", "Kimberli", "Kleopátra", "Kriszta", "Ladiszla", "Leona", "Liliána", "Lola", "Lukrécia", "Laksmi", "Leonarda", "Lilianna", "Lolita", "Lula", "Lamberta", "Leonetta", "Lilibell",
			"Lolli", "Lulu", "Lana", "Leonóra", "Lilien", "Lóna", "Luna", "Lara", "Leontina", "Liliom", "Lora", "Lüszi", "Larcia", "Leopolda", "Liliróza", "Lorella", "Larina", "Leopoldina", "Lilla", "Lorena", "Larissza", "Leóti", "Lilu", "Loréna", "Lartia", "Letícia", "Lina", "Lorenza", "Latinka", "Letisa",
			"Linda", "Lorett", "Laura", "Létó", "Linett", "Loretta", "Laurencia", "Letta", "Linetta", "Loriana", "Lauretta", "Letti", "Linka", "Lorin", "Lavínia", "Levendula", "Lióra", "Lorina", "Lea", "Levízia", "Lívia", "Lotte", "Léda", "Lia", "Liviána", "Lotti", "Leila", "Liána", "Livianna", "Luca",
			"Lejla", "Lícia", "Liza", "Lúcia", "Léla", "Lida", "Lizandra", "Luciána", "Lelle", "Lídia", "Lizavéta", "Lucilla", "Léna", "Lígia", "Lizbett", "Lucinda", "Léni", "Lili", "Lizett", "Ludmilla", "Lenka", "Lilia", "Lizetta", "Ludovika", "Lenke", "Lilian", "Lizi", "Lujza", "Lenóra", "Lilián",
			"Lízia", "Lujzi", "Mábel", "Manfréda", "Mariann", "Mátka", "Méráb", "Mimi", "Misell", "Mabella", "Manga", "Marianna", "Maura", "Mercédesz", "Mimóza", "Moána", "Madlen", "Manka", "Marica", "Maurícia", "Meredisz", "Mína", "Modeszta", "Madléna", "Manna", "Mariella", "Maxima", "Méri", "Mínea", "Moira",
			"Magda", "Manolita", "Mariett", "Maximilla", "Merilin", "Minerva", "Molli", "Magdaléna", "Manon", "Marietta", "Méda", "Merima", "Minka", "Mona", "Magdó", "Manszvéta", "Marika", "Medárda", "Messzua", "Minna", "Móna", "Magdolna", "Manuela", "Marilla", "Médea", "Méta", "Minóna", "Móni", "Magnólia", "Manuéla",
			"Marina", "Médi", "Metella", "Mira", "Mónika", "Magorka", "Manuella", "Marinella", "Megán", "Métisz", "Míra", "Montika", "Mahália", "Manyi", "Marinetta", "Meggi", "Metta", "Mirabel", "Morella", "Maida", "Mara", "Marinka", "Melani", "Mia", "Mirabell", "Morgána", "Maja", "Marcella", "Marion", "Melánia",
			"Mici", "Mirabella", "Muriel", "Majoranna", "Marcellina", "Marióra", "Melina", "Miett", "Miranda", "Múzsa", "Makrina", "Maréza", "Mariska", "Melinda", "Mietta", "Mirandella", "Maléna", "Margarét", "Marita", "Melióra", "Mihaéla", "Mirandola", "Malka", "Margaréta", "Marléne", "Melissza", "Mikolt", "Mirandolína", "Málna", "Margaretta",
			"Márta", "Melitta", "Mila", "Mirázs", "Malvin", "Margarita", "Martina", "Melizand", "Milágrosz", "Mirea", "Malvina", "Margit", "Martinella", "Melodi", "Milda", "Mirella", "Mályva", "Margita", "Martinka", "Melódia", "Miléna", "Miriam", "Manda", "Margitta", "Masa", "Meluzina", "Miletta", "Mirjam", "Mandola", "Margó",
			"Mása", "Mendi", "Milica", "Mirjána", "Mandorla", "Mari", "Matild", "Menodóra", "Milka", "Mirka", "Mandula", "Mária", "Matilda", "Menta", "Milla", "Mirtill", "Nadett", "Nedda", "Nimfa", "Nadia", "Nefelejcs", "Nina", "Nadin", "Nelda", "Ninell", "Nadinka", "Nélia", "Ninett", "Nádja", "Nella",
			"Ninetta", "Nanae", "Nelli", "Ninon", "Nanda", "Nenszi", "Niobé", "Nandin", "Nerella", "Nisá", "Nanett", "Nerina", "Noa", "Nanetta", "Neste", "Noélia", "Naomi", "Neszrin", "Noella", "Naómi", "Neszta", "Noémi", "Napsugár", "Netta", "Nola", "Nárcisz", "Netti", "Nomin", "Narcissza", "Néva",
			"Nona", "Narina", "Nia", "Nóna", "Narmin", "Niké", "Nóra", "Násfa", "Niki", "Norberta", "Nasztázia", "Nikodémia", "Nóri", "Natali", "Nikol", "Norina", "Natália", "Nikola", "Norka", "Natasa", "Nikolett", "Norma", "Nauszika", "Nikoletta", "Nausziká", "Níla", "Nauzika", "Nilla", "Nyeste", "Oana",
			"Olga", "Opál", "Orsika", "Odett", "Oliána", "Opika", "Orsolya", "Odetta", "Olimpia", "Orália", "Oszvalda", "Odil", "Olina", "Orchidea", "Otília", "Odília", "Olinda", "Orgona", "Ottilia", "Ofélia", "Oliva", "Oriána", "Oxána", "Oktávia", "Olívia", "Orsi", "Őszike", "Pálma", "Perpétua", "Priszcilla",
			"Palmira", "Petra", "Prudencia", "Palóma", "Petronella", "Psziché", "Pamela", "Petrónia", "Paméla", "Petúnia", "Pamína", "Pilár", "Pandora", "Pintyőke", "Pandóra", "Pírea", "Panka", "Piri", "Panna", "Pirit", "Panni", "Piros", "Paszkália", "Piroska", "Pasztorella", "Placida", "Patrícia", "Platina", "Paula", "Polda",
			"Pauletta", "Polett", "Paulin", "Pólika", "Paulina", "Polina", "Peggi", "Polixéna", "Pelágia", "Polla", "Pénelopé", "Polli", "Peónia", "Pompília", "Peregrina", "Pompónia", "Perenna", "Poppea", "Perla", "Primula", "Ráchel", "Rézi", "Roxán", "Ruperta", "Rafaéla", "Ria", "Roxána", "Ruszalka", "Rafaella", "Riana",
			"Róza", "Ruszlána", "Ráhel", "Rika", "Rozál", "Rut", "Rahima", "Ríka", "Rozália", "Ruzsinka", "Rajmonda", "Rikarda", "Rozalinda", "Rajmunda", "Ripszima", "Rózamari", "Rákhel", "Rita", "Rozamunda", "Rákis", "Ritta", "Rozanna", "Ramira", "Riza", "Rozi", "Ramóna", "Roberta", "Rozina", "Rasdi", "Robertin",
			"Rozita", "Rea", "Robertina", "Rozmarin", "Rebeka", "Robina", "Rozmaring", "Rege", "Robinetta", "Rozvita", "Regina", "Rodé", "Rózsa", "Réka", "Rodelinda", "Rózsi", "Relinda", "Romána", "Röné", "Rella", "Romi", "Rubi", "Relli", "Romina", "Rubin", "Remény", "Rominett", "Rubina", "Reményke", "Romola",
			"Rubinka", "Renáta", "Ronett", "Rudolﬁna", "Réta", "Ronetta", "Ruﬁna", "Rezeda", "Rovéna", "Rúna", "Sába", "Sanel", "Sáron", "Sirá", "Sudárka", "Sáfély", "Santál", "Seherezádé", "Siváni", "Sugár", "Sáfrány", "Sára", "Seila", "Skolasztika", "Sugárka", "Sakira", "Sári", "Sejla", "Stefánia", "Salomé",
			"Sarlott", "Senon", "Steﬁ", "Salóme", "Sarolt", "Seron", "Stella", "Samuella", "Sarolta", "Sifra", "Sudár", "Szabella", "Szelli", "Sziéna", "Szkilla", "Szabina", "Szellő", "Sziglind", "Szoﬁ", "Szabrina", "Szellőke", "Szilárda", "Szoﬁa", "Szafﬁ", "Szelma", "Szille", "Szóﬁa", "Szaﬁra", "Szemerke", "Szilvána",
			"Szoﬁnett", "Szalima", "Szemira", "Szilvesztra", "Szofrónia", "Szalóme", "Szemirámisz", "Szilvia", "Szolanzs", "Szalvia", "Szemőke", "Szimka", "Szona", "Szamanta", "Szendi", "Szimóna", "Szonja", "Szamira", "Szendike", "Szimonett", "Szonóra", "Szamóca", "Szendile", "Szimonetta", "Szoraja", "Szandra", "Szénia", "Szindi", "Szorina", "Szanna",
			"Szenta", "Színes", "Szörénke", "Szantána", "Szépa", "Szinta", "Sztavrula", "Szantina", "Szépe", "Szintia", "Sztefani", "Száva", "Szera", "Szira", "Sztella", "Szavanna", "Szereﬁna", "Szíra", "Szulamit", "Szavéta", "Szeréna", "Szirén", "Szulejka", "Szavina", "Szerénke", "Sziringa", "Szulikó", "Szávitri", "Szeverina", "Szirka",
			"Szulita", "Szébra", "Szibill", "Szirom", "Szultána", "Szederke", "Szibilla", "Szironka", "Szüntüké", "Szedra", "Szidalisz", "Szixtin", "Szüvellő", "Szegfű", "Szidi", "Szixtina", "Szvetlána", "Szelina", "Szidónia", "Szkarlett", "Tábita", "Teodolinda", "Tília", "Tulipán", "Tácia", "Teodóra", "Tilla", "Tullia", "Taciána", "Teodózia",
			"Tímea", "Tünde", "Taisza", "Teofánia", "Timona", "Tündér", "Tália", "Teoﬁla", "Timótea", "Tündi", "Talita", "Teónia", "Tina", "Tűzvirág", "Támár", "Tercia", "Tinetta", "Tamara", "Teréz", "Tinka", "Tamina", "Tereza", "Tíra", "Tanázia", "Teréza", "Tirca", "Tanita", "Terézia", "Tíria", "Tánya",
			"Teri", "Tirza", "Tara", "Terka", "Titánia", "Tarzícia", "Tertullia", "Titanilla", "Tatjána", "Tessza", "Titti", "Tavasz", "Tétisz", "Tittína", "Tavaszka", "Tia", "Tóbia", "Tea", "Tiana", "Tóbia", "Tegza", "Tiána", "Tomazina", "Tekla", "Tiara", "Topáz", "Telma", "Tícia", "Toszka", "Témisz",
			"Ticiána", "Triniti", "Téna", "Tifani", "Trixi", "Ténia", "Tikva", "Trudi", "Teobalda", "Tilda", "Túlia", "Uljána", "Úna", "Urszula", "Uzonka", "Ulla", "Uránia", "Urzula", "Ulrika", "Urbána", "Urzulina", "Üdvöske", "Vadvirág", "Vélia", "Veszta", "Villő", "Víta", "Valencia", "Velmira", "Véta",
			"Vilma", "Vitália", "Valentina", "Vendelina", "Vetúria", "Vincencia", "Vitolda", "Valéria", "Vénusz", "Via", "Viola", "Viviána", "Vanda", "Vera", "Vica", "Violenta", "Vivianna", "Vanessza", "Veránka", "Viki", "Violet", "Vivien", "Vanilla", "Verbéna", "Vikta", "Violett", "Vivika", "Varínia", "Veréna", "Viktória",
			"Violetta", "Vrinda", "Vásti", "Verita", "Viktorina", "Viorika", "Vulﬁa", "Vaszília", "Veron", "Vilászini", "Virág", "Veca", "Verona", "Vilhelma", "Virgília", "Véda", "Veronika", "Vilhelmina", "Virgínia", "Veronka", "Vilja", "Xavéria", "Xenodiké", "Zaﬁra", "Zeﬁra", "Zenge", "Zinaida", "Zója", "Zahira", "Zéla",
			"Zengő", "Zinajda", "Zolna", "Zája", "Zelda", "Zenina", "Zinka", "Zoltána", "Zakária", "Zélia", "Zenke", "Zita", "Zomilla", "Zalánka", "Zelina", "Zenkő", "Ziva", "Zonga", "Zamﬁra", "Zelinda", "Zenóbia", "Ziza", "Zora", "Zamira", "Zelinde", "Zenta", "Zizi", "Zóra", "Zara", "Zeline",
			"Zeta", "Zoárda", "Zorina", "Zazi", "Zelinke", "Zetta", "Zoé", "Zorinka", "Zdenka", "Zelka", "Zia", "Zohara", "Zorka", "Zea", "Zella", "Zília", "Zoja", "Zosja", "Zelli", "Zille", "Zöldike", "Zelma", "Zimra", "Zulejka", "Zelmira", "Zina", "Zsadányka", "Zsazsa", "Zsinett", "Zsuzsánna",
			"Zsaklin", "Zselinke", "Zsóﬁ", "Zsuzsi", "Zsálya", "Zsella", "Zsóﬁa", "Zsuzska", "Zsanett", "Zselyke", "Zsóka", "Zsüliett", "Zsanin", "Zseni", "Zsolna", "Zsüsztin", "Zsanina", "Zseraldin", "Zsorzsett", "Zsanka", "Zseráldin", "Zsuzsa", "Zsanna", "Zseraldina", "Zsuzsanna"};

		public static string[] csaladnevek = new string[] {
			"Masoviai", "Benczur", "őlvedi", "őri", "őSchuck", "Aaron", "Aba", "Aba nembéli", "Abban", "Abdul-Wahab", "Abonyi", "Abos", "Ábrahám", "Abril", "Äcs", "Ádám", "Adamcsik", "Adámy", "Ágoston", "Ajtai", "Ajtai-Baricsa", "Aknai", "Akpenejoseph", "Albert", "Alboiu", "Alburquerquei", "Alexandrovich", "Almási", "Almássy", "Ambrózai",
			"Ambrus", "Andaházy Kasnya", "Andrási", "Angelosz", "Angyal", "Angyalné-Koszorús", "Ángyán", "Anjou", "Ansbach-i", "Antal", "Antalné Putnik", "Apágyi", "Apáti", "Appel", "Appel-Arató", "Arabacan", "Aracsi", "Araczki", "Aradi", "Aragóniai", "Aranyi", "Aranyos", "Arató", "Aricioglu", "Árkosi", "Áron", "Arpa", "Árpád-házi", "Ascsillán", "Aszalós",
			"Asztalos", "Átyim", "Aubert", "Auer", "Auschwitz", "Ausztriai", "Auth", "Azari", "Bőhm", "Babai", "Babcsány", "Babenbergi", "Bács", "Bacsik", "Bácskay", "Bacsó", "Baczur", "Bagdi", "Bagi", "Bagics", "Bagó", "Bagocsi", "Bajaki", "Bajcsi", "Bajkai", "Bajkó", "Bajor", "Bajtai", "Bak", "Bakó",
			"Bakon", "Bakonyi", "Bakos", "Baksa", "Bakti", "Bakusz", "Bal", "Balassa", "Balaz", "Balázs", "Balázsik", "Báles", "Bali", "Bálint", "Balláné-Gyói", "Balo", "Balog", "Balogh", "Baloghné Szőcs", "Bán", "Bandrus", "Bandur", "Banffy", "Bánhegyi", "Bánki", "Bánkuti", "Bánóczy", "Banyai", "Bapcsánné-Pekár", "Barabás",
			"Barabássy", "Bárándiné Török", "Bárány", "Baranyai", "Baranyi", "Baráth", "Barcsa", "Barcsik", "Bardi", "Bardocz", "Bárdos", "Baricz", "Bárkányi", "Barkó", "Barla", "Barna", "Barnáné", "Barnáné Török", "Báró Vadnay", "Bárocz", "Barta", "Bartalis", "Bartek", "Bartha", "Bartók", "Barton", "Bartos", "Bartus", "Bartusné-Lovácsi", "Basa",
			"Básthy", "Bata", "Batári", "Báthory", "Batta", "Battenbergi", "Battonyai", "Bauer", "Bausche", "Bayer", "Becker", "Becsei", "Bedecs", "Bedekovich", "Beik", "Bek", "Beke", "Békefi", "Béldi", "Bélei", "Bella", "Bellovics", "Béna", "Bencsik", "Bencze", "Benczi", "Benczur", "Bendő", "Bendzsák", "Bene",
			"Benedek", "Benedekl", "Benkő", "Benke", "Benkéné", "Bense", "Benson", "Bényei-Csáky", "Bercsényi", "Bere", "Berea", "Berecz", "Bereczki", "Bereczky", "Bereczky Bársony", "Berei", "Berényi", "Béres", "Berkecz", "Berkes", "Berkeszi", "Berky", "Bernát", "Bernáth", "Berta", "Bertalan", "Besker", "Beszédes", "Beszterczey", "Beta",
			"Bezdán", "Bezzeg", "Bicsak", "Bicskei", "Biczók", "Bieber", "Bielz", "Bigai", "Bihari", "Bihariné-Szakács", "Bija", "Bilav", "Bilbija", "Bilkei", "Billitz", "Birloni", "Biro", "Birtalan", "Bitto", "Blahó", "Blaskó", "Blenessy", "Blézer", "Blount", "Blumenschein", "Bóbis", "Boc", "Bocz", "Boda", "Bódi",
			"Bodis", "Bódizs", "Bodnár", "Bodó", "Bodóczki", "Bodor", "Bodri", "Bodrog", "Boér", "Boga", "Bogár", "Bogdán", "Bognár", "Bogyor", "Böhm", "Bohony", "Bohonyi", "Bohus", "Böjte", "Bojthe", "Bók-Gallai", "Bóka", "Bokor", "Bokor-Nagy", "Boldi", "Boldizsár", "Boldog", "Boleyn", "Bollok", "Bolváry",
			"Bolyki", "Bóna", "Bondar", "Bongya", "Bonus", "Bor", "Borbás", "Borbáth", "Borbély", "Bordás", "Bordi", "Bordy", "Borgulya", "Bori", "Böröcz", "Boromisza", "Boros", "Boroska", "Bors", "Borsi", "Borsik", "Borsos", "Borszéki", "Boruzs", "Bosnyák", "Bota", "Botházi", "Botos", "Bourbon", "Bourbon–Pármai",
			"Bourbon–Szicíliai", "Bout", "Bowes-Lyon", "Bözödi", "Bozsics", "Bozsoki", "Bozsoky-Soós", "Bozzay", "Brandenburgi", "Brandl", "Braun", "Bráz", "Brebe", "Brezvai", "Brief", "Brok", "Bronz", "Brücher", "Bruder", "Brunner", "Brunnerné Berta", "Bruzsa", "Buck", "Buda", "Budaházy", "Budai", "Budavári", "Bugariu", "Bugyik", "Bujáki",
			"Buka", "Bükki", "Bükkös", "Bukkosi", "Bukodi", "Bulhardt", "Bumasz", "Buna", "Burai", "Buránszki", "Burány", "Burányi", "Burcs", "Burczin", "Buresch", "Burián", "Burjan", "Burszán", "Buruncz", "Bus", "Busák", "Busca", "Buzgo", "Candale-i", "Capet", "Cazac-Hamza", "Celle-i", "Cetean", "Châtillon", "Cherbezan",
			"Chis", "Chudenici Cernin", "Chudonici Cernin", "Cillei", "Ciora", "Costea-Kolozsvari", "Cotoi", "Courot", "Courtenay", "Croy-Airaines", "Csőke", "Csaba", "Csabai", "Csáfordi", "Cságolya", "Csák", "Csaki", "Csáky", "Csalár", "Csányi", "Csaplár", "Csapó", "Csaszar", "Császiné-Kiss", "Csatai", "Csató", "Csécs", "Csegőldi", "Cseh", "Csejtey",
			"Cseke", "Csékei", "Csekéné-Kovács", "Csendes", "Csenki", "Csente", "Csenteri", "Csepcsényi", "Csepei", "Cser", "Csere", "Cserey", "Csergő", "Cseri", "Csermák", "Csernak", "Csernus", "Csernyik", "Csete", "Cseterki", "Csibi", "Csicsó", "Csiffáry", "Csiffáry", "Csifó", "Csige", "Csik", "Csík Huszák", "Csike", "Csikesz",
			"Csíki", "Csíkné-Gábli", "Csikós", "Csillag", "Csillik", "Csima", "Csincsi", "Csire", "Csiri", "Csirke", "Csízi", "Csizmadia", "Csoba", "Csobay", "Csóka", "Csókási", "Csom", "Csoma", "Csomán", "Csonka", "Csontos", "Csorba", "Csordás", "Csörgő", "Csóri", "Csótai", "Csóti", "Csuhai", "Csuka", "Csurgay",
			"Csurgó", "Csurpek", "Csuvik", "Csúzi", "Czáboczky Abaházi", "Czakó", "Czanik", "Czapp", "Czárné", "Czékmási", "Czifra", "Czika", "Czikmantori", "Czina", "Czinder", "Czinege", "Czinkóczi", "Czirják", "Czombál", "Czorn", "Czovek", "Czudor", "Dakó", "Daku", "Dalanics", "Dali", "Dalos", "Dancová", "Dancsó", "Daniel",
			"Daniné", "Dankó", "Danó", "Danyi", "Dapsy", "Darabosné", "Daradics", "Darányi", "Darázs", "Darkó", "Darmtedter", "Daroczi", "Daróczy", "Darvasi", "Dauda", "Dauner", "Dávid", "de Alburquerque", "de Castilla y Haro", "de Castro", "de Haro", "de Lara", "de Meneses", "de Saint-Omer", "de Wavrint", "Deák", "Debreczeni", "Dékány", "Delján", "Demeny",
			"Demeter", "Dénes", "Dér", "Detari", "Dévai", "Dezső", "Dienes", "Dimitrova", "Dinnyési", "Dinteanu", "Dóbiás", "Dobo", "Dobos", "Dobos-Szabo", "Dobosy", "Dobrán", "Dobronyi", "Dobsa", "Dobson", "Dohnál", "Dojcsák", "Domán", "Dombi", "Döme", "Domián", "Dominek", "Domján", "Donka", "Dorina", "Dorneanu",
			"Dorner", "Dorosmai", "Dósa", "Doszkocs", "Dr Balogh", "Dr Széll", "Dr. Balogh", "Dr. Kollár", "Dr. Ujj", "Dr.Balogh", "Dr.Ujlaky", "Drahos", "Drávucz", "Draxler", "Draxler", "Druta", "Dubóczky", "Dubován", "Dudas", "Duffy", "Dukaina", "Dunai", "Dundita", "Dunst", "Durecz", "Dürgő", "Durgó", "Durkó", "Durst", "Durucz",
			"Dvariecki", "Ecsenyi", "Edelényi-Szabó", "Egei", "Égető", "Egri", "Egyed", "Együd", "Eiben", "Eiler", "Eisenkrammer", "Élő", "Elefant", "Elek", "Engi", "Erős", "Erősné", "Ercsei", "Erd", "Erdős", "Erdei", "Erdélyi", "Erdész", "Érdi", "Erki", "Erlitz", "Erős", "Esek", "Ésik", "Esslinger",
			"Estei", "Eszes", "Eszinger", "Eszlári", "Eszterle", "Éter", "Fábián", "Fábri", "Fadgyas", "Faltusz", "Faluvégi", "Fancsik", "Faragó", "Fáriné", "Farkas", "Farkas-Vuk", "Farmasi", "Farnady", "Fássy", "Fata", "Fazekas", "Fecser", "Féderer", "Fedora", "Fehér", "Fehérvári", "Feil", "Feith", "Fejes", "Fekete",
			"Fekete-Kun", "Fél", "Felber", "Felföldi", "Félix", "Fenyvesi", "Feranecz", "Ferenc", "Ferencz", "Ferencz-Nagy", "Ferenczi", "Ferkó", "Feró", "Festő", "Feuerbach", "Ficzere", "Fidel", "Fien", "Figeczky", "Filep", "Finszter", "Finta", "Fió", "Fischer", "Fleisz", "Florescu", "Flórián", "Flóruczó", "Fodoca", "Fodor",
			"Fogarasi", "Fogarassy", "Fogas", "Fógel", "Foki", "Földesi", "Földvári", "Föll", "Forgon", "Forian", "Fóris", "Forrai", "Fótyi", "Franch", "Francia", "Franciaországi", "Frank", "Frank Földvári", "Frank rokon", "Freund", "Frey", "Frigy", "Fróman", "Fügedi", "Fülőp", "Fülöp", "Füredi", "Furka", "Fust", "Fuszko",
			"Futó", "Füzesi", "Gőbel", "Gőcze", "Gaál", "Gaálné Czákler", "Gábor", "Gábor-Németh", "Gabriel", "Gács", "Gafiulin", "Gafiulina", "Gafrik", "Gajda", "Gál", "Gál-Áfra", "Galaczi", "Galambos", "Galgóczi", "Gallina", "Gálné", "Gálos", "Gamos", "Garai", "Garamszegi", "Garas", "Garay", "Garda", "Gárdi", "Gárdos",
			"Gartai", "Gáspár", "Gáspár-Babos", "Gasparim", "Gaszler", "Gazdag", "Gebauer", "Géber", "Gebhardt", "Gebri", "Géczi", "Gelei", "Gelencser", "Geleta", "Gelu", "Georgiu", "Gera", "Gerencsér", "Gerencsérné", "Gergácz", "Gergely", "Gergelyfi", "Gero", "Gerst", "Gesztesi", "Gherman", "Gilányi", "Gimpel", "Giordano", "Glonczi",
			"Gódi", "Goerz-Tirol-i", "Gogolák", "Gombkötő", "Gombócz", "Gombos", "Gomez", "Gömöri", "Gönczi", "Göncziné Szabó", "Gönczy", "Gondi", "Goóg", "Goralszki", "Görbe", "Gornyec", "Gortvay", "Görzi", "Gránicz", "Grási", "Grecu", "Gréczi", "Greff", "Gregorné-Szepesi", "Grob", "Grósz", "Gruber", "Gubala", "Gubán", "Gubis",
			"Guj", "Gula", "Güldner", "Gulyás", "Gúthy", "Gutyina", "Győrfi", "Győri", "Győry Siposs", "Gyarmathy", "Gyarmati", "Gyatyel", "Gyebnár", "Gyebrovszki", "Gyenes", "Gyepesi", "Gyertyánosi", "Gyetvai", "Gyikóné", "Gyimesi", "Gyökös", "Gyöngy", "Gyöngyössyné-Nagy", "Gyorfi", "György", "Györi", "Györkei", "Györki", "Györkös", "Gyovai",
			"Gyurcsány", "Gyuricska", "H Kincses", "Habok", "Habsburg", "Habsburg–Estei", "Habsburg–Lotaringiai", "Habsburg–Tescheni", "Habsburg–Tiroli", "Hadak Ura", "Hadfi", "Hadobás", "Haduzsán", "Hadvári", "Hagymássy", "Hahn", "Hajasné-Varga", "Hajba", "Hajci Haja", "Hajdu", "Hajduné Farkas", "Hajkó", "Hajmássy", "Hajnal", "Hajnik", "Halasi", "Halász", "Halaszy", "Halfinger", "Halmosiné-Árvai",
			"Háló", "Hamar", "Hámori", "Hamvas", "Hanák", "Handa", "Handari", "Hankó", "Hanzel", "Harangozo", "Harant", "Haranth", "Haraszti", "Harasztosi", "Harcos", "Harcsa", "Hargitay", "Harkai", "Harkányiné-Fülöp", "Harmath", "Harsony", "Hart", "Hartweg", "Hasas", "Hasulyó", "Haszák", "Hasznos", "Hatos", "Hatvani", "Havasi",
			"Havril", "Hdear", "Hebelt", "Hegedős", "Hegedüs", "Héger", "Hegyi", "Heit", "Hellebrandt", "Helwirth", "Henez", "Henrietta", "Henter", "Henyusz", "Herczeg", "Herczig", "Heresznyei", "Herman", "Hermann", "Hersman", "Hertling", "Heszler", "Hetényi", "Hetyei", "Hevesi", "Hévízi", "Hideg", "Hidvéghy", "Hídvégi", "Higyed",
			"Hillebrand", "Hipik", "Hliva", "Hóbor", "Hodonicki", "Hodor", "Hodruszky", "Hoffer", "Hoffmann", "Hogelücht", "Hohenstauf", "Hohenstaufen", "Hol", "Hollandus", "Holocsi", "Holubek", "Hölzl", "Hommer", "Homoki", "Homolai", "Homorodi", "Hőnig", "Hoós", "Hora", "Horányi", "Horn", "Hornáőek", "Horovici Hradists", "Horvat", "Horváth",
			"Horváth-Molnár", "Horváth-Takács", "Horváthné Filyó", "Horváthné Meixner", "Horváthné Rudovics", "Horváthné Rysavy", "Horwat", "Howard", "Hrazdovics", "Hrotkóné-Bálint", "Hudacsek", "Hugyik", "Hulban", "Hulin", "Hulkó", "Hullman", "Hum", "Hun-Bodó", "Hunyadi", "Huppert", "Huppert Hamvas", "Hürkec", "Hurton", "Husz", "Huszar", "Huszka", "Huszti", "Hutu", "Hutvágner", "Ianovici Ianovic",
			"Igaz", "Ignácz", "Igrinyi", "Igz", "Ihász", "Iklandi Vadady Filep", "Iklódi", "Illár", "Illés", "Illésné", "Illyés", "Ilyés", "Ilykó", "Imre", "Imrich", "Incze", "Iordache", "Ippler", "Irsai", "Ispan", "Istán", "Istok", "Istokovics", "István", "Iszlai", "Iván", "Ivanic", "Jablonovszki", "Jaczkó", "Jagelló",
			"Jagoschütz", "Jáhner", "Jakab", "Jakob", "Jaksa", "Jaksics", "Jakus", "Jámbor", "Jami", "Jancsika Hamza", "Jancsó", "Janek", "Jani", "Janics", "Janisch", "Jankovics", "János", "Jánosi", "Janvary", "Járadi", "Járosi", "Jaroszló", "Jasztrab", "Javorne Gulacsi", "Jávorszki", "Jéga Szabó", "Jehodek", "Jékey", "Jenci", "Jenei",
			"Jenes", "Jeney", "Jerabek", "Jeszenszky", "Jobbagy", "John", "Jónás", "Jónis", "Jordán", "Jóvián", "Jovon", "Józsa", "József", "Judit És Csaba", "Juhász", "Juhász-Nagy", "Juhászné Fehér", "Juhos", "Juncanaru", "Jurák", "Juszko Román", "Kőházy", "Kőhegyi", "Kőrösi", "Kőrösiné", "Kőszegi", "Kővágó", "Kővári", "Kabai", "Kacsora",
			"Kádár", "Käding", "Kaibás", "Kajány", "Kajári", "Kajárik", "Kalamanos", "Kalánka", "Kali", "Kaliszi", "Kalitics", "Kállai", "Kalló", "Kálmán", "Kalmár", "Kalster", "Kaluczky", "Kamocsai", "Kamptner", "Kanalos", "Kancsár", "Káncz", "Kanda", "Kankovszky", "Kántor", "Kapási", "Kaposy", "Kappant", "Kaprinay", "Kaptás",
			"Kaputa", "Kapy", "Kara", "Karacsony", "Karaffa", "Karakas", "Karaszi", "Karaszne Kovacs", "Karazsi", "Kardos", "Karintiai", "Kárner", "Karóczkai", "Károly", "Károlyi", "Kárpáti", "Kárpisz", "Karsai", "Kártyik", "Kása", "Kasikné Mihálik", "Kássa", "Kassai", "Kaszàs", "Kasztíliai", "Kátai", "Katalin", "Katona", "Katona", "Katonai",
			"Kaucz", "Kaufman", "Kavarnyik", "Kávásy", "Kazinczy", "Keőkéš", "Kecskeméti", "Kecskés-Antalné", "Keddie", "Kedu", "Kedves", "Keiner", "Kékkői", "Kel", "Kelemen", "Kelemenné Horváth", "Kelemenné-Vass", "Keller", "Kellner", "Keméndy", "Kémenea", "Kendi", "Kenéz", "Kepenyes", "Keppinger", "Kerék", "Kerekes", "Kerékgyártó", "Kereskedő", "Keresztényi",
			"Keresztes", "Keresztúri", "Kerka", "Kertész", "Kerti", "Keszeg", "Kétyi", "Keviczky", "Kézdi", "Khon", "Kicska", "Kilián", "Kilyén", "Kimmel", "Király", "Kirchner", "Kirilla", "Kirtyán", "Kis", "Kisantal", "Kisdeák", "Kisfalusi", "Kisházy", "Kiss", "Kiss Erdélyi", "Kiss-Révy", "Kissné", "Kissné Borgulya", "Kissné-Kertész", "Kisvárday-Papp",
			"Kivanc", "Kk", "Klajner", "Klanicza", "Klausz", "Klein", "Klemen", "Klevei", "Klezli", "Klimko", "Klotz", "Klug", "Kmety", "Knoblauch", "Ko", "Köbli", "Köböl", "Kóbor", "Kobza", "Kocsány", "Kocsárdy", "Kocserha", "Kocsi", "Kocsis", "Kocsmárné", "Kócsó", "Koczkáné", "Koczmann", "Ködösné-Hajdu", "Koffol",
			"Kohon", "Kokai", "Kolek", "Köllő", "Kollar", "Koller", "Kolman", "Kolovics", "Költő", "Kömőves", "Komiszár", "Komnena", "Komnénosz", "Komori", "Koncsánszki", "Koncz", "Kondás", "Kondor", "Kondorosi", "Konstantinovna", "Konta", "Kontor", "Kónya", "Könyvtár", "Koósz", "Kopasz", "Kopócsy", "Koppány", "Korb", "Korcsik",
			"Kormányos", "Körmendi", "Körmőczi", "Kornyik", "Korodi", "Koronczi", "Kőrös", "Körösi", "Körözsi", "Körtélyesi", "Kós", "Kósa", "Koska", "Kóta", "Köteles", "Kóti", "Kovács", "Kovács Lászlóné", "Kovacsics", "Kovacsóczy", "Kováts", "Kövesdi Sándorné", "Kozár", "Kozári", "Kozek", "Kozma", "Kozmáné Bődi", "Krajczár", "Krán", "Kránicz",
			"Krans", "Kráz", "Krèth", "Kristály", "Kristóf", "Krisztián", "Kröell - Dulay", "Kromes", "Krupánszky", "Ksz", "Kubík", "Kubínyi", "Kucián", "Kucman", "Kuffartné-Mikó", "Kugler", "Kühner", "Kui", "Kuki", "Kukorica", "Kuktin", "Kulacs", "Kulcsár", "Kulich", "Kun", "Kun-Horváth", "Kundi", "Kundl", "Kunos", "Kurai",
			"Kurcz", "Kuri", "Kúron", "Kürti", "Kurucsai", "Kurucz", "Kuszi", "Kutasi", "Kuti", "Kutya", "Kuzted", "Lőb", "Lőrinc", "Lőrincz", "Lőrinczi", "Lőrinczné", "Laczi", "Laczkó", "Laczkó Csabáné", "Ladányi", "Ladik", "Lajkó", "Lakatos", "Laki", "Lancasteri", "Lang", "Laszkarisz", "László", "Lavotha", "Lázár",
			"Lazaridisz", "Leányvári", "Lecei", "Leczki", "Ledneczki", "Leidecker", "Lekli", "Lélfai", "Lempelné", "Lenart", "Lénárth", "Lencse", "Lencsés", "Lendvai", "Lengyel", "Lesko", "Lestyánszki", "Lévai", "Lévay", "Libár", "Liborné", "Lilien", "Linczer", "Lipcsei", "Lippai", "Liptai", "Liptói", "Liska", "Lizán-Nagy", "Lóránt",
			"Lorenzovics", "Lörincz", "Losonc", "Losonczi", "Lotaringiai", "Lovas", "Lovász", "Lovászi", "Lövei Natália", "Lovikov", "Lozsi", "Lucza", "Luda", "Lukács", "Lukácsi Windegg", "Luxemburgi", "Lvovics", "Macskássy", "Maczó", "Madar", "Madarasi", "Madarász", "Madzsar", "Magányos", "Magasházy", "Magdics", "Maghar", "Magyar", "Magyari", "Majkó",
			"Major", "Majoros", "Makainé Udvardy", "Makkai", "Makkai-Arany", "Maklári", "Makra", "Makranczi", "Maksai", "Málnai", "Malnasi", "Mandel", "Manuel", "Már", "Marcibál", "Marczin", "Margin", "Marie", "Marika", "Marinet", "Márka", "Márki", "Markó", "Márkos", "Márkus", "Maródi", "Marosvölgyi", "Maróth", "Maróy", "Martin",
			"Martinák", "Márton", "Martonné", "Maszlay", "Masznyik", "Mata", "Máté", "Máté -Birta", "Mateescu", "Mátéfi", "Matei", "Matejcsek", "Mathe", "Matkó", "Matosics", "Mátrahegyi", "Mátray", "Matus", "Matusik-Kühl", "Mátyás", "Mayer", "Mazuláné Burka", "Mecklenburg–Strelitz-i", "Medveczki", "Medvegy", "Megyer", "Megyes", "Mehes", "Meiszter", "Melegh",
			"Melheritz", "Mellár", "Mellischek", "Menyhárt", "Menyhért", "Meráni", "Mercsákné Simon", "Mereteiné-Matosics", "Méri", "Meskó", "Mester", "Mészáro", "Mészáros", "Mészöly", "Metz", "Metzger", "Mezei", "Mezosi", "Miavecz", "Michel", "Mihalcz", "Mihálicz", "Mihalidesz", "Mihalik", "Mihalko", "Mihály", "Mihályné", "Mihók", "Mihókné", "Mihovics",
			"Mijin", "Mike", "Miklós", "Miklósné-Mészáros", "Milinker", "Minorits", "Miskó", "Miskolczi", "Miskovics", "Mislainé-Szántó", "Mocsari", "Módi", "Mogyorosi", "Mohay", "Mojzi", "Moldovan", "Molnár", "Molnárné Kvakk", "Monostori", "Montferrati", "Montpellier-i", "Moric", "Móricz", "Mórocz", "Morosini", "Morta", "Morvay", "Morzsinai", "Mosdósi", "Mositz",
			"Mosolygó", "Mozga", "Mozsgai", "Mozsolics", "Mracsko", "Mucsi", "Muhi", "Mulicz", "Müller", "Mura", "Muretics", "Murguly", "Muszka", "N", "N.N.", "Nadar", "Nádas", "Nádaskai", "Nadori", "Nagy", "Nagy Némedi", "Nagy-Gáll", "Nagy-Hevesi", "Nagy-Tóth", "Nagyi", "Nagyné", "Nagyné György", "Nagyné Tóth", "Nagyné-Banadics", "Nagyszegi",
			"Nanasi", "Nándoriné", "Náray", "Naszvadi", "Navrea", "Necefor", "Négyesi", "Nemes", "Nemes-Ortutay-S", "Német", "Németh", "Németi", "Neszmélyi", "Neuberger", "Neubrant", "Nevem", "Néveri", "Nikli", "Nirschné-Henn", "Nistor", "Novák", "Novák-Nagy", "Nyári", "Nyemcsók", "Nyerges", "Nyers", "Nyiczky", "Nyiri", "Nyisztorné Szabó", "Nyitrai",
			"Nyul", "Obsitos", "Ocsovai", "Ódor", "of Portalegre", "Oláh", "Oláhné Marosi", "Oláhné-Csomor", "Olajos", "Olexa", "Oltyean", "Ölyüs", "Ömböli", "Onaka", "Ondok", "Ónodi", "Onoferné Pelle", "Opitz", "Orbán", "Ordog", "Ordogh", "Oriskó", "Orléans-i", "Orodán", "Orosz", "Orseolo", "Ország", "Osvath", "Oszwald", "Ottlik",
			"Ottrok", "Özbahadir", "Özv.Szilvási", "P Toth", "Paál", "Pacsika", "Paczók", "Pados", "Páger", "Pahn", "Pajer", "Pajkos", "Pákai", "Pakányi", "Pákozdi", "Paksi", "Paku", "Pál", "Palagyi", "Palatinus", "Páles", "Pálfalvi", "Pálfy", "Páli", "Pálinkás", "Páll", "Pallaga", "Pallos", "Pannoniay", "Pányi",
			"Pap", "Pap Knapec", "Pap-Gaudi", "Papné", "Papp", "Pappné-Szegszárdi", "Parad", "Parásó", "Parditka", "Paré", "Páros", "Parr", "Pásztor", "Patai", "Patak", "Pataki", "Patakiné Szenik", "Patik", "Patkós", "Patterman", "Paulicsné-Tóth", "Paulovkin", "Páviács", "Paxián", "Peczi", "Pégan", "Pej", "Pekker", "Pekter", "Pelbárt",
			"Pelegrin", "Pelyvás", "Penisoara", "Péntek", "Peres", "Peresa", "Perger", "Pető", "Petőné-Utasi", "Péter", "Péterfi", "Pethes", "Peti", "Petra", "Petrás", "Petrik", "Petrinovics", "Petroczi", "Petrovics", "Pfalz–Neuburgi", "Pfirt-i", "Phillips", "Piast", "Piffer", "Pilcz", "Pinczés", "Pintér", "Pintye", "Pirampel", "Piri",
			"Pistai", "Pivó", "Pócs", "Pòczos", "Pokol", "Polacsek", "Polgár", "Polgári", "Polka", "Polonyi", "Polyak", "Polyoka", "Pomerániai", "Pongor", "Pongrácz", "Pónuzs", "Poór", "Pop", "Pór", "Pörneczi", "Poroszka", "Poroszlai", "Portugáliai", "Pósa", "Posovszki", "Póth", "Pozsár", "Pozsgai", "Pozsgay", "Pozsonyi",
			"Prátserné Varjas", "Predenici Predenic", "Preiner", "Preisz", "Prekesztics", "Přemysl", "Prepszl", "Pribitek", "Prien", "Princz", "Prodan", "Prokopecz", "Prónai", "Pucher", "Pudes", "Purgel", "Puska", "Puskás", "Püspök", "Pusztai", "Putz", "Płocki", "Rőth", "Raáb", "Rába", "Rabi", "Rabóczki", "Race", "Rács", "Racsek",
			"Racsmány", "Rácz", "Radáné-Nagy", "Rádi", "Radics", "Radics Parthus", "Radna", "Radócz", "Radomir", "Ráduly", "Raffai", "Raffay", "Ragályi-Sártory", "Rajnai", "Rajzfilmek", "Rákli", "Rakonczay", "Rákos", "Rakovszki", "Rápóti-Fekete", "Rapp", "Rausch", "Redli", "Regősné-Almási", "Regéczy", "Reichardt", "Reichenberger", "Reimesch", "Reisch", "Reischl",
			"Reiter", "Reményi", "Reményik", "Ren", "Rendi", "Reszler", "Retek", "Rétfalvi", "Réti", "Révainé-Antal", "Révész", "Revóczky", "Rezes", "Rheinfeldi", "Richolm", "Rigó", "Rocskár", "Rohn", "Rojas", "Róka", "Romovai Krinecki", "Rompos", "Rónai", "Ronyecz", "Rostas", "Róthné Csábráki", "Rozsa", "Rózsáné", "Rozsnyai", "Rubi",
			"Rubosné Kun", "Russ", "Russo", "Sabirowa", "Sacc", "Safar", "Sághy", "Sági", "Sajdik Juhász", "Sajó", "Salamon", "Salati", "Salcáné", "Saleh", "Saliga", "Sallai", "Sallay", "Sándor", "Sándor-Szcsotka", "Santa", "Sánz", "Sárdy", "Sarkadi", "Sárkány", "Sárközi", "Sárközi-Dömötör", "Sarnyai", "Sasfalvi", "Sass", "Sasvári",
			"Savanyóné-Németh", "Savoyai", "Schadegg Maria", "Schirling", "Schmitt", "Schotsch", "Schrancz", "Schuck", "Schultz", "Schumacher", "Schumi", "Schütt", "Schwadlwnka", "Schwartz", "Sebők", "Sebestény", "Sebestyén", "Sedlák", "Seitán", "Seprődi", "Sere", "Seremet", "Seres", "Serfőző", "Sersli", "Setét", "Sevik", "Seymour", "Sforza", "Shoham",
			"Siák", "Simányi", "Simeonovich", "Simion", "Simó", "Simon", "Simonek", "Simonfi", "Singer", "Sinka", "Sinko", "Sinkovics", "Sipos", "Sisak", "Skoff", "Smeták", "Smid", "Sochnikova", "Sofranko", "Sógor", "Sohár", "Solnzev", "Solnzeva", "Soltesz", "Solymos", "Solymosi", "Somai", "Somlyódy", "Somodi", "Somogyi",
			"Somogyi-Szántó", "Somogyiné Zsédöly", "Somoskövy", "Soós", "Soproniné", "Sorban", "Sörfőző", "Sóstai", "Sovány", "Spegelberger", "Spencer", "Spitzer", "Sportika", "Stampf", "Stan", "Starosta", "Stefán", "Sterczel", "Stewart", "Stibálné", "Stiedl", "Stigler", "Stiny", "Stojcsics", "Stormbom", "Straka", "Strobl", "Stuart", "Stuberné-Pál", "Stum",
			"Stumper", "Styaszni", "Styles", "Suba", "Subicz", "Sudár", "Sugár", "Suhart", "Suko", "Sukola", "Sukosd", "Süle", "Süli", "Sulyok Eiler", "Surányi", "Sütő", "Suto", "Sved", "Sventner", "Świdnicai", "Swynford", "Szőcs", "Szőke", "Szőkéné-Horváth", "Szőllősi", "Szabad", "Szabados", "Szabadosné Posta", "Szabó", "Szabóné",
			"Szabóné-Hugyák", "Szabóné-Jeviczki", "Szabóné-Pálfi", "Szádoczky", "Szájer", "Szak", "Szakács", "Szakácsné Kun", "Szakál", "Szakolczai", "Szalai", "Szalainé Kovács", "Szalamia", "Szalavári", "Szalay", "Szali", "Szalinszky", "Szalma", "Szalmás", "Szalonnás", "Szalontai", "Szaniszló", "Szántai", "Szantó", "Szanyi", "Szár", "Szárnya", "Szarvas", "Szasz", "Szász-Major",
			"Szászországi", "Szatmári", "Szável", "Szebeni", "Szécsényi", "Szécsi", "Szedlacsek", "Szegő", "Szegedi", "Szegedy", "Szegi", "Szeibert", "Szeidler", "Szekely", "Szekeres", "Szekeresné-Juhász", "Szelei-Kis", "Szeles", "Szelka", "Széll", "Szemeti", "Szénási", "Szendrei", "Szendrey", "Szenes", "Szentgyörgyi", "Szenti", "Szentmíklósí", "Szentpétery", "Szeöke",
			"Szép", "Szepesi", "Szepesváry", "Szepesy", "Széplaki", "Szerecsen", "Szerelő", "Szeremy", "Szerencsés", "Szicher", "Szigeti", "Szigetvári", "Sziki", "Sziklafy", "Sziklai", "Sziklainé", "Szikszai", "SzikszainéüKallósi", "Szikszay", "Szilágyi", "Szilágyi-Palko", "Szilvássy", "Szilveszter", "Sziráczki", "Szirmai", "Szirtes", "Szitó", "Szittya", "Sziveli", "Szlávy",
			"Szmolenszky", "Szodorai", "Szögi", "Szoke", "Szokol", "Szókovács", "Szöllősi", "Szombati", "Szömörei", "Szónok", "Szopos", "Szóráth", "Szovik", "Sztavinovszky", "Sztyéhlik", "Szucs", "Szücsné Cziráki", "Szudi", "Szuha", "Szuhányiné Busa", "Szuszitsné-Pintér", "Szvetlik", "Szvitek", "Tabi", "Taganyi", "Tageldin", "Tajti", "Takács", "Takácsi-Nagy", "Takácsné-Szabó",
			"Takár", "Takó", "Talaber", "Tálas", "Tallér", "Tallian", "Tallodi", "Tamas", "Tánczos", "Tankó", "Tapaszto", "Tapody", "Tar", "Tarcsa", "Tarcsiné", "Tarczal", "Tarczi", "Tárczy", "Tarján", "Tarpay", "Társas", "Tarsoly", "Taskovics", "Tassy", "Tatár", "Tátrai", "Tausz", "Tavi", "Técsi", "Tégény",
			"Tekse", "Telegdi", "Teleky", "Téllez de Meneses", "Temesvari", "Templer", "Tene", "Terbe", "Terenyei", "Terna", "Ternyák", "Teslér", "Tézsla", "Thar", "Tihanyi", "Tikvicki", "Till", "Timár", "Timkó", "Tischler", "Tiszai", "Titkos", "Tivadar", "Tkacsuk", "Tóbiás", "Todeilă", "Tökölyiné-Szkulszki", "Toldi", "Tolnay", "Toma-Vég",
			"Tomai", "Tomkovics", "Tomposné-Erdeős", "Tonigold", "Törőcsik", "Tordai", "Töreki", "Tornay", "Török", "Toth", "Tothné-Karaffa", "Tóthné-Toldi", "Tőtős", "Tövisháti", "Traversari", "Tribel", "Tringer", "Tropcici Mirhovsky", "Tuboly", "Tücsökné", "Tudor", "Tulézi", "Turcsik", "Turi", "Turjanica", "Turkosi", "Turner", "Turny", "Turoczi", "Tusjakné Kasuba",
			"Tuskánné-Juhász", "Tüske", "Tuson-Bódi", "Tyukász", "Udvardy", "Udvarhelyi", "Ugroczi", "Újházi", "Ujj", "Újlaki", "Ujszászi", "Ujvari", "Ujváriné", "Újváry", "Ulovai Ulova", "Ulrich", "Unbescheid", "Untener", "Unyi", "Urai-Uray", "Urbán", "Ursinyi", "Utasi", "Utószülött", "Üveges", "Uzoni", "vacsi", "Váczi", "Váczy", "Vadai",
			"Vági", "Vágvölgyi", "Vajas", "Vajda", "Valko", "Valkovszki", "Valois", "Vámos", "Vandróczki", "Vangyia", "Vanjur", "Vanya", "Váradi", "Varanka", "Varga", "Varga-Kővári", "Vargáné Bodó", "Vargáné Ilyés", "Vargyas", "Várhalmi", "Várhelyi", "Vári", "Varjassy", "Varju", "Városi", "Városiné", "Varró", "Vas", "Vásári", "Vaskó",
			"Vaskuti", "Vass", "Vastag", "Vasvári", "Vay", "Vayda", "Vázsonyi", "Veber", "Vecsei", "Vecsernyés", "Végel", "Végh", "Végső", "Velko", "Vén", "Venczel", "Vendégh", "Véniger", "Vér", "Verőné", "Verbovszkiné", "Veres", "Veress", "Vermes", "Vernon", "Vernyel", "Vetési", "Vetróné-Laczkó", "Vezendi", "Vezsenyi",
			"Vida", "Vidó", "Vietórisz", "Vigh", "Vikor", "Vili", "Vilk", "Vimmer", "Vincze", "Vinek", "Vinkler", "Vinkó", "Viola", "Virág", "Virágné", "Visz", "Viszkok", "Visznai", "Vitalis", "Vitályos", "Vitéz-Farkas", "Vittinger", "von Hortenau", "Vörös", "Vucsetics", "Vugodits", "Wagner", "Walter", "Wátz", "Waum",
			"Wéber", "Wenczel", "Werderics", "Wichow", "Wieland", "Winklerné", "Wittelsbach", "Witzing", "Wohner", "Xy", "Yorki", "Yurevich", "Yuriyevych", "Zacher", "Zádor", "Zádori", "Zagoni", "Zagyi", "Zahorán", "Zahorján", "Zakar", "Zalai", "Zaray", "Zárug", "Zatyko", "Zbiskó", "Zelenka", "Zémann", "Zengő", "Zentai",
			"Zielmann", "Zimán", "Zimonyi", "Zóka", "Zöld", "Zoldi", "Zoldos", "Zolnainé-Siklósi", "Zombori", "Zonda", "Zrinyi", "Zsadányi", "Zsebe", "Zsebik", "Zsédely", "Zsednainé Szegfü", "Zsédől", "Zsigmond", "Zsiros", "Zsivicsar", "Zsivu", "Zsoldos", "Zsupan", "Zsurka", "Zubor", "Zudor Nagy", "Zuti", "Zwickel", "Zwickl", "Zwillinger"
		};


		public static string getName(int gender)
		{
			return getName(gender, "");
		}

		public static string getName(int gender, string nameToSkip)
		{
			string name = "";

			while (name == "" || name == nameToSkip)
			{
				Thread.Sleep(3);
				name = csaladnevek[new Random().Next(0, csaladnevek.Length)];
			}

			Thread.Sleep(3);
			name += " " + (gender == 0 ? fiunevek[new Random().Next(0, fiunevek.Length)] : lanynevek[new Random().Next(0, lanynevek.Length)]);

			return name;
		}

		public static string[] getNames(int gender)
		{
			string[] names = new string[2];
			names[0] = getName(gender);
			names[1] = getName(1, names[0].Split(' ')[0]);

			return names;
		}

		
	}
}
